version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "appium-remote-debugger"
      - match:
          dependency_name: "chai"
      - match:
          dependency_name: "xpath"
